name: medicare
description: A comprehensive patient mobile app for healthcare management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_messaging: ^15.2.9
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  
  # PDF Handling & File Operations
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.2
  share_plus: ^11.0.0
  permission_handler: ^12.0.1
  
  # HTTP & Networking
  http: ^1.1.2
  dio: ^5.4.0
  
  # Video Calling (Placeholder for integration)
  agora_rtc_engine: ^6.3.0
  
  # Location Services
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  
  # Image Handling
  image_picker: ^1.0.4
  
  # Notifications
  flutter_local_notifications: ^19.3.0
  
  # Rating & Reviews
  flutter_rating_bar: ^4.0.1
  
  # Calendar
  table_calendar: ^3.0.9
  
  # Animations
  lottie: ^3.3.1
  
  # QR Code (Updated to compatible packages)
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
