name: medicare
description: A comprehensive patient mobile app for healthcare management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.10
  
  # State Management
  provider: ^6.1.5

  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.0
  flutter_svg: ^2.0.17
  cached_network_image: ^3.3.2

  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  
  # PDF Handling & File Operations
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  permission_handler: ^11.1.0
  
  # HTTP & Networking
  http: ^1.4.0
  dio: ^5.8.0+1

  # Video Calling (Placeholder for integration)
  agora_rtc_engine: ^6.5.2

  # Location Services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Image Handling
  image_picker: ^1.1.2

  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Rating & Reviews
  flutter_rating_bar: ^4.0.0

  # Calendar
  table_calendar: ^3.1.9
  timezone: ^0.10.1

  # Animations
  lottie: ^2.7.0
  
  # QR Code (Updated to compatible packages)
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  