name: medicare
description: A comprehensive patient mobile app for healthcare management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animated_widgets: ^1.1.0
  flutter_animate: ^4.2.0
  flutter_carousel_slider: ^1.1.0

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_messaging: ^15.2.9

  # State Management
  provider: ^6.1.5

  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.0
  flutter_svg: ^2.0.17
  cached_network_image: ^3.3.2

  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

  # PDF Handling & File Operations
  flutter_pdfview: ^1.4.1+1
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  permission_handler: ^12.0.1

  # HTTP & Networking
  http: ^1.4.0
  dio: ^5.8.0+1

  # Video Calling (Placeholder for integration)
  agora_rtc_engine: ^6.5.2

  # Location Services
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # Image Handling
  image_picker: ^1.1.2

  # Notifications
  flutter_local_notifications: ^19.3.0

  # Rating & Reviews
  flutter_rating_bar: ^4.0.0

  # Calendar
  table_calendar: ^3.1.9

  # Animations
  lottie: ^3.3.1

  # QR Code (Updated to compatible packages)
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/banner1.png
    - lib/assets/banner2.png
    - lib/assets/banner3.png
    - lib/assets/dashboard_banner.png
    - lib/assets/prescription.png
    - lib/assets/stethoscope.png
    - lib/assets/stars.png
    - lib/assets/consultation.png
    - lib/assets/icons/chat.png
    - lib/assets/icons/settings.png
